### ISSUE TITLE
GLIBC_2.28 not found RHEL7 latest Milestone M003 2023051201

### ISSUE THREAD

**Issue by drapiti** [Linuxfabrik/monitoring-plugins#673]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

latest Milestone M003 on rhel 7 now giving the following error.

[93392] Error loading Python lib '/usr/lib64/nagios/plugins/libpython3.9.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib64/nagios/plugins/libpython3.9.so.1.0)

All checks have the same issue.
**CentOS or RHEL does not officially support this and provides glibc version 2.17 as official version.**

### Steps to reproduce - Plugin call

All plugins identical problem

### Steps to reproduce - Data

Install latest plugins on rhel 7

### Environment

Rhel 7

### Plugin Version

2023051201

### Additional Information

**CentOS or RHEL does not officially support this and provides glibc version 2.17 as official version.**

**Comment by markuslf** [comment]
The plugins for RHEL 7 are compiled on CentOS 7 using Python 3.8. Your error message points to Python 3.9. Looks like your binaries were installed from the wrong repo path or weren't updated at all (just a guess).

I also tested all RHEL OS packages again - installed them according to https://repo.linuxfabrik.ch/monitoring-plugins/ in fresh VMs and ran `/usr/lib64/nagios/plugins/cpu-usage`. The results:
* CentOS 7: Works
* Rocky 8: Works
* Rocky 9: Works

**Comment by drapiti** [comment]
Hi I've checked some other RHEL7 systems and they all seem to have the same problem using the official RHEL 7 repos and the linixfabrik repo. Looking into it.. Found some information here https://access.redhat.com/discussions/3244811 definatley don't want to modify the RHEL7 native glibc version. Not sure why CentoS 7 does not have this problem but most of our systems are RHEL7/RHEL8.

**Comment by drapiti** [comment]
Done a fresh install of rhel7 and recompiled from source. It is now working.

**Comment by markuslf** [comment]
I have now compiled the plugins for RHEL 7 on a RHEL 7 instead of CentOS and uploaded it to the mirror. Maybe you can give the new rpm (`-2`) a try.

**Comment by drapiti** [comment]
> I have now compiled and packaged the plugins for RHEL 7 on a RHEL 7 instead of CentOS and uploaded it to our repo server. Maybe you can give [the new rpm](https://repo.linuxfabrik.ch/monitoring-plugins/rhel/7/release/noarch/linuxfabrik-monitoring-plugins-2023051201-2.noarch.rpm) (`-2`) a try.

Will do.

**Comment by markuslf** [comment]
Ok, closing for now. Thanks for testing and your feedback.
